import type { ResearchCase } from '../rows.js'

// Written from research/agreed/turkey/provinces.md and nothing else, one file per research
// case, which the country's file composes (SB-232).

export const CASE: ResearchCase = {
  document: 'provinces',
  // Every province, coded as ISO's platform codes it and named as NVI's directory
  // names it, both read in research/agreed/turkey/provinces.md (SB-210).
  regions: [
    { code: 'TR-01', parent: null, name: 'Adana' },
    { code: 'TR-02', parent: null, name: 'Adıyaman' },
    { code: 'TR-03', parent: null, name: 'Afyonkarahisar' },
    { code: 'TR-04', parent: null, name: 'Ağrı' },
    { code: 'TR-05', parent: null, name: 'Amasya' },
    { code: 'TR-06', parent: null, name: 'Ankara' },
    { code: 'TR-07', parent: null, name: 'Antalya' },
    { code: 'TR-08', parent: null, name: 'Artvin' },
    { code: 'TR-09', parent: null, name: 'Aydın' },
    { code: 'TR-10', parent: null, name: 'Balıkesir' },
    { code: 'TR-11', parent: null, name: 'Bilecik' },
    { code: 'TR-12', parent: null, name: 'Bingöl' },
    { code: 'TR-13', parent: null, name: 'Bitlis' },
    { code: 'TR-14', parent: null, name: 'Bolu' },
    { code: 'TR-15', parent: null, name: 'Burdur' },
    { code: 'TR-16', parent: null, name: 'Bursa' },
    { code: 'TR-17', parent: null, name: 'Çanakkale' },
    { code: 'TR-18', parent: null, name: 'Çankırı' },
    { code: 'TR-19', parent: null, name: 'Çorum' },
    { code: 'TR-20', parent: null, name: 'Denizli' },
    { code: 'TR-21', parent: null, name: 'Diyarbakır' },
    { code: 'TR-22', parent: null, name: 'Edirne' },
    { code: 'TR-23', parent: null, name: 'Elazığ' },
    { code: 'TR-24', parent: null, name: 'Erzincan' },
    { code: 'TR-25', parent: null, name: 'Erzurum' },
    { code: 'TR-26', parent: null, name: 'Eskişehir' },
    { code: 'TR-27', parent: null, name: 'Gaziantep' },
    { code: 'TR-28', parent: null, name: 'Giresun' },
    { code: 'TR-29', parent: null, name: 'Gümüşhane' },
    { code: 'TR-30', parent: null, name: 'Hakkari', isoName: 'Hakkâri' },
    { code: 'TR-31', parent: null, name: 'Hatay' },
    { code: 'TR-32', parent: null, name: 'Isparta' },
    { code: 'TR-33', parent: null, name: 'Mersin' },
    { code: 'TR-34', parent: null, name: 'İstanbul' },
    { code: 'TR-35', parent: null, name: 'İzmir' },
    { code: 'TR-36', parent: null, name: 'Kars' },
    { code: 'TR-37', parent: null, name: 'Kastamonu' },
    { code: 'TR-38', parent: null, name: 'Kayseri' },
    { code: 'TR-39', parent: null, name: 'Kırklareli' },
    { code: 'TR-40', parent: null, name: 'Kırşehir' },
    { code: 'TR-41', parent: null, name: 'Kocaeli' },
    { code: 'TR-42', parent: null, name: 'Konya' },
    { code: 'TR-43', parent: null, name: 'Kütahya' },
    { code: 'TR-44', parent: null, name: 'Malatya' },
    { code: 'TR-45', parent: null, name: 'Manisa' },
    { code: 'TR-46', parent: null, name: 'Kahramanmaraş' },
    { code: 'TR-47', parent: null, name: 'Mardin' },
    { code: 'TR-48', parent: null, name: 'Muğla' },
    { code: 'TR-49', parent: null, name: 'Muş' },
    { code: 'TR-50', parent: null, name: 'Nevşehir' },
    { code: 'TR-51', parent: null, name: 'Niğde' },
    { code: 'TR-52', parent: null, name: 'Ordu' },
    { code: 'TR-53', parent: null, name: 'Rize' },
    { code: 'TR-54', parent: null, name: 'Sakarya' },
    { code: 'TR-55', parent: null, name: 'Samsun' },
    { code: 'TR-56', parent: null, name: 'Siirt' },
    { code: 'TR-57', parent: null, name: 'Sinop' },
    { code: 'TR-58', parent: null, name: 'Sivas' },
    { code: 'TR-59', parent: null, name: 'Tekirdağ' },
    { code: 'TR-60', parent: null, name: 'Tokat' },
    { code: 'TR-61', parent: null, name: 'Trabzon' },
    { code: 'TR-62', parent: null, name: 'Tunceli' },
    { code: 'TR-63', parent: null, name: 'Şanlıurfa' },
    { code: 'TR-64', parent: null, name: 'Uşak' },
    { code: 'TR-65', parent: null, name: 'Van' },
    { code: 'TR-66', parent: null, name: 'Yozgat' },
    { code: 'TR-67', parent: null, name: 'Zonguldak' },
    { code: 'TR-68', parent: null, name: 'Aksaray' },
    { code: 'TR-69', parent: null, name: 'Bayburt' },
    { code: 'TR-70', parent: null, name: 'Karaman' },
    { code: 'TR-71', parent: null, name: 'Kırıkkale' },
    { code: 'TR-72', parent: null, name: 'Batman' },
    { code: 'TR-73', parent: null, name: 'Şırnak' },
    { code: 'TR-74', parent: null, name: 'Bartın' },
    { code: 'TR-75', parent: null, name: 'Ardahan' },
    { code: 'TR-76', parent: null, name: 'Iğdır' },
    { code: 'TR-77', parent: null, name: 'Yalova' },
    { code: 'TR-78', parent: null, name: 'Karabük' },
    { code: 'TR-79', parent: null, name: 'Kilis' },
    { code: 'TR-80', parent: null, name: 'Osmaniye' },
    { code: 'TR-81', parent: null, name: 'Düzce' },
  ],
  regionsFrom: {
    document: 'provinces',
    codes: { source: 'isoSubdivisions', label: 'iso-3166-2-tr-provinces' },
    names: {
      source: 'provinceDirectorates',
      label: 'nvi-province-directorates',
    },
  },
  sources: {
    isoSubdivisions: {
      url: 'https://www.iso.org/obp/ui/#iso:code:3166:TR',
      name: 'ISO Online Browsing Platform, TR - Türkiye',
      read: '2026-09-15',
    },
    provinceDirectorates: {
      url: 'https://www.nvi.gov.tr/il-mudurlukleri',
      name: 'Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü, İl Nüfus ve Vatandaşlık Müdürlükleri',
      read: '2026-09-15',
    },
  },
}
